### ISSUE TITLE
[Bug] Hide at completion hides the bar right away

### ISSUE THREAD

**Issue by zaken** [raingart/AutoHideDownloadsBar-extension#5]
![image](https://user-images.githubusercontent.com/21025134/41806254-e125b192-76c2-11e8-9885-617ade117e86.png)

If I understand correctly these 2 options should make the extension hide the downloads bar 5 seconds after a download is complete but show it during download.

The bar is hidden instantly upon starting the download for me.

**Comment by raingart** [comment]
strangely, I'm working correctly. And what do you have in the console output?

**Comment by zaken** [comment]
I'm sorry for late response, was super busy. So steps to reproduce are:
1. Start a download.
2. Cancel the download.
3. Start a download again and it will hide before finishing.

**Comment by raingart** [comment]
это связано с тем что задержка по сути таймер. И если он запущен

**Comment by raingart** [comment]
corrected [#5](https://github.com/raingart/AutoHideDownloadsBar-extension/commit/6666db1e6e773cafb96b23251ff8240b0bcc02f8)
