### ISSUE TITLE
ext is removed from the extension store

### ISSUE THREAD

**Issue by ctf0** [raingart/AutoHideDownloadsBar-extension#9]

**Comment by raingart** [comment]
Yes, I turned it off. 

There are errors in the code. As I correct then I will publish

**Comment by ctf0** [comment]
plz ping me when u re-enable it, thanx

**Comment by raingart** [comment]
@ctf0 
![Screenshot from 2020-02-07 13-09-32](https://user-images.githubusercontent.com/13064767/74024814-41c6bc00-49ab-11ea-9055-c93745d3a8e3.png)

I don’t know how long it will take.

I also removed pupup download management. It is poorly written and works. And I consider it useless garbage.

**Comment by ctf0** [comment]
np, thanx for ur work
